blacklist:
  - /server
  - //set
locale:
  config-reload: "Configuration successfully reloaded."
  config-reload-failed: "Failed to reload configuration."
  message: "&7[&8&lâœš&7]&7 {0} executed {1}"
  prefix: "&7[&a&lCreative&fCraft&7]&f"
  list: "Current spies: {0}"
  list-none: "None"
  toggle-off: "You are no longer &aspying&f on commands network-wide."
  toggle-on: "You are now &aspying&f on commands network-wide."
show-own-commands: true
spies: {}
